name: Release

on:
  release:
    types: [published]

env:
  package_type: module

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build packs
        run: npm run pack

      - name: Extract tag version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Substitute fields in module.json
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          version: ${{ steps.get_version.outputs.version-without-v }}
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

      - name: Create module.zip
        run: zip -r module.zip . --exclude ".git/*" --exclude ".github/*" --exclude "node_modules/*" --exclude "src/*"

      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "module.json,module.zip"
          tag: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}